#index:
#   path: /
#  controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET

app_homepage:
  path: /
  controller: App\Controller\MainController::index

view_books:
  path: /create_book/view_books
  controller: App\Controller\BookController::all
